name: "Composite Sample"

runs:
  using: "composite"
  steps:
    - name: echo
      run: |
        pwd
        echo "${GITHUB_ACTION_PATH}"
        cat "${GITHUB_ACTION_PATH}/branch.yml"

      shell: bash

