name: "Composite Sample"

outputs:
  targets:
    value: ${{ steps.hoge.outputs.targets }}

runs:
  using: "composite"
  steps:
    - name: echo
      id: hoge
      shell: bash
      run: |
        TARGETS=()

        TARGETS+=("dev")
        TARGETS+=("stg")
        TARGETS+=("prd")

        targets=$(printf '%s\n' "${TARGETS[@]}" | jq -R . | jq -s -c .)
        echo "targets=$targets" >> $GITHUB_OUTPUT
