name: "Composite Sample"

outputs:
  targets:
    value: ${{ steps.hoge.outputs.targets }}

runs:
  using: "composite"
  steps:
    - name: echo
      id: hoge
      shell: bash
      run: |
        TARGETS=()

        TARGETS+=('{"name":"dev","desc":"開発"}')
        TARGETS+=('{"name":"stg","desc":"ステージング"}')
        TARGETS+=('{"name":"prd","desc":"本番"}')

        targets=$(printf '%s\n' "${TARGETS[@]}" | jq -R . | jq -s -c .)
        echo $targets
        echo "targets=$targets" >> $GITHUB_OUTPUT
